# Outputs configuration
outputs:
  bin:
    artifactName: python
    spec:
      friendlyName: Python Interpretor
      description: A Python interpretor using Brython.
      author: Onofficiel
      copyright: Copyright (C) Onofficiel 2024.
      subsys: cli
      version: 1.0
      icon: null

# Package information
package:
  name: python
  category: cli

  icon16: ./assets/icon16.png
  icon32: ./assets/icon32.png

  featureRequirements: []
  depends: []

  min_os_version: 300000
  max_os_version: 400000