# Outputs configuration
outputs:
  bin:
    artifactName: tsc
    spec:
      friendlyName: Typescript Compiler
      description: A Typescript Compiler.
      author: Onofficiel | Microsoft
      copyright: Copyright (C) Onofficiel 2024.
      subsys: cli
      version: 1.2
      icon: null

# Package information
package:
  name: tsc
  category: cli

  icon16: ./assets/icon16.png
  icon32: ./assets/icon32.png

  featureRequirements: []
  depends: []

  min_os_version: 300000
  max_os_version: 400000