# Outputs configuration
outputs:
  bin:
    artifactName: border
    spec:
      friendlyName: Border
      description: A simple, multitab and modern web browser.
      author: Onofficiel
      copyright: Copyright (C) Onofficiel 2024.
      subsys: gui
      version: 110.1
      icon: null

# Package information
package:
  name: border
  category: accessories

  icon16: ./assets/icon16.png
  icon32: ./assets/icon32.png

  featureRequirements: []
  depends: []

  min_os_version: 300000
  max_os_version: 400000