# Toolchain version
version: 1.0

# Project Settings
project:
  type: "wrt"
  name: "Basic CLI Application"

# Compiler settings
compiler:
  name: wrtc
  options:
    useBabel: true
    useTerser: true
    startupClass: HelloWorldApplication
    entryFile: ./src/main.js

# Hacky things
hacks:
  shiftArgv: false

# Outputs configuration
outputs:
  bin:
    artifactName: helloworld
    spec:
      friendlyName: Hello World
      description: Simple command line program
      author: Windows 96 Team
      copyright: Copyright (C) Author 2023.
      subsys: cli
      version: 1.1
      icon: null

# Package information
package:
  name: sample
  category: cli

  icon16: ./assets/icon16.png
  icon32: ./assets/icon32.png

  featureRequirements: []
  depends: []

  min_os_version: 300000
  max_os_version: 400000